apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-efs-wordpress-ap
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0d6a1bfe7c9e05343::fsap-REPLACE_WITH_YOURS
    volumeAttributes:
      path: "/"
