apiVersion: v1
kind: Pod
metadata:
  name: efs-mount-test
  namespace: wordpress
spec:
  containers:
  - name: tester
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: efs
      mountPath: /mnt/efs
  volumes:
  - name: efs
    persistentVolumeClaim:
      claimName: wordpress-efs-pvc
  restartPolicy: Never
